"""remove unique key from user_id in otp

Revision ID: 38baf82deb65
Revises: 43b61e34cd74
Create Date: 2026-09-26 01:02:44.924707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38baf82deb65'
down_revision: Union[str, Sequence[str], None] = '43b61e34cd74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('otps_user_id_key'), 'otps', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('otps_user_id_key'), 'otps', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
