"""add created at and updated at in leads

Revision ID: e7eaaf55ba03
Revises: a0838fe10033
Create Date: 2026-09-27 10:13:16.098396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7eaaf55ba03'
down_revision: Union[str, Sequence[str], None] = 'a0838fe10033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('leads', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'updated_at')
    op.drop_column('leads', 'created_at')
    # ### end Alembic commands ###
